### ISSUE TITLE
Fix how tests are provided when LOMAP is installed

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/Lomap#20]
I'm working on migrating LOMAP to `setup.cfg` (and moving to pip-installability). However, the current `setup.py` has some strange behavior that I think needs to change.

### What LOMAP does now

Currently, `setup` receives `packages=find_packages() + ['test']`. This means that you get 2 packages installed into your `site-packages`: `lomap` and `test`. This copies the test files into `site-packages/test/`, which:

1. Is a really bad usage of namespace, since the contents of `site-packages/test/` [will be whichever package last tried to install something as a package called `test`](https://stackoverflow.com/a/65904451/).
2. Is unusable anyway, since it is shadowed by [standard library `test` package](https://docs.python.org/3/library/test.html), which you'll get on `import test` (unless you did something freaky with your environment).

### Option 1: Make tests a subpackage

Move `test/` -> `lomap/tests/`. It gets installed as usual. Things can be imported from `lomap.tests`. This is what we do with all our other packages.

### Option 2: Include tests via MANIFEST and package-data

This leaves the files where they are currently, but should make tests available at `lomap.tests`. Honestly, this isn't an approach I use, and my attempts to get things like this to work in the past were a bit of a headache.

### Option 3: Don't include tests

We could just say that the tests have to be downloaded separately. I'm not a fan of this.

---

Personally, I'd vote for option 1. I don't think this counts as an API break (technically, we're moving tests to a different namespace, but since it was impossible to access tests with a default Python setup, I don't think it is a problem.)

**Comment by IAlibay** [comment]
Since the test files are < 1 MB, I'd vote for Option 1. We should make sure we don't go too large on the package though.

**Comment by richardjgowers** [comment]
Yep sounds like a plan

**Comment by IAlibay** [comment]
If I remember correctly, a vast majority of our space-consuming files are SDFs. Could we just gzip them? That should make the package tiny.

**Comment by dwhswenson** [comment]
> Could we just gzip them?

I'm not sure how straightforward this would be -- a lot depends on how flexible RDKit file-loading is with types. I'm not opposed to someone doing it, but I don't want it to block the PR on `setup.cfg` / getting ready for PyPI (which this will be a part of).

**Comment by IAlibay** [comment]
> > Could we just gzip them?
> 
> I'm not sure how straightforward this would be -- a lot depends on how flexible RDKit file-loading is with types. I'm not opposed to someone doing it, but I don't want it to block the PR on `setup.cfg` / getting ready for PyPI (which this will be a part of).

We can do it as a separate thing, but this should work just fine (except maybe Windows, would have to try?):

```
>>> import gzip
>>> inf = gzip.open('data/actives_5ht3.sdf.gz')
>>> with Chem.ForwardSDMolSupplier(inf) as gzsuppl:
...    ms = [x for x in gzsuppl if x is not None]
```
