### ISSUE TITLE
Radial argument fails to create radial network

### ISSUE THREAD

**Issue by DreamCykl** [OpenFreeEnergy/Lomap#24]
Hi,

I've been trying to use the radial function of lomap and have been having issues. I am using the same set of ligands in /tests/radial and the functions in /examples/example_radial_graph.py.

```py
import lomap
db_mol = lomap.DBMolecules('/root/Downloads/Lomap/lomap/tests/radial/', output=True, radial=True, hub = 'ejm44.mol2')
strict, loose = db_mol.build_matrices()
strict_numpy = strict.to_numpy_2D_array()
loose_numpy = loose.to_numpy_2D_array()
nx_graph = db_mol.build_graph() 

# Drawing the network
import networkx as nx
import matplotlib.pyplot as plt
pos = nx.spring_layout(nx_graph)
nx.draw(nx_graph, pos)
nx.draw_networkx_labels(nx_graph, pos)
plt.show()
```
Creates the following graph:
![image](https://user-images.githubusercontent.com/122363535/225370577-07f1315a-bc9f-4886-9a96-55208056bc71.png)

Running with radial=False and no hub ligand selected creates the same, non-radial network.

**Comment by richardjgowers** [comment]
hi @DreamCykl this is sort of working as intended.  There's a similarity cutoff (default 0.4) which prevents edges that are considered "bad".  So initially a radial graph is constructed, then some edges deleted and a connected graph then built on top of the remnants of the radial graph.

If you want to force a radial graph at any cost, then you can set the `cutoff=0.0`, e.g.:

`db_mol = lomap.DBMolecules('radial/', output=True, radial=True, cutoff=0.0)`

this will still create a graph with cycles, so depending on your opinion it might not be a radial graph, but it definitely contains a radial graph
