### ISSUE TITLE
computing full matrix for radial maps with hub provided

### ISSUE THREAD

**Issue by arjun-nufc** [OpenFreeEnergy/Lomap#28]
Is it really necessary to compute the full MCS matrix for radial maps when a hub ligand is provided?  It seems like you would just need to compute the array of values for the N ligands to the hub compound, or am i missing something?

**Comment by arjun-nufc** [comment]
Nevermind, I think that this is related to issue #24, and that explains why you still need to compute the full matrix of similarities.  I am looking for a simple hub and spoke radial graph.  it looks like this is possible with `cutoff=0.0` and `allow_tree=True`.

**Comment by arjun-nufc** [comment]
This is still an issue though - when trying to explore larger numbers of synthetic possibilities in a real world application, a simple hub and spoke radial graph is going to be needed.  While this is possible as mentioned above, it still requires computation of the full Nx(N-1)/2 similarities.  This gets to be prohibitively slow pretty quickly.

**Comment by IAlibay** [comment]
@arjun-nufc I believe that the functionality you need is present in the `openfe` toolkit. If you want to raise an issue there with the task you're trying to do I'm pretty sure we can give you a code snippet that'll achieve a radial network with the lomap mapper & scorer in a minimum number of evaluations.

**Comment by richardjgowers** [comment]
@arjun-nufc this gist shows how to create a radial network using openfe and lomap together: https://gist.github.com/richardjgowers/79451ed3d698618125f9fa1b3dd82e52  This will only require the N-1 calculation of MCS/score as expected.

Making the traditional Lomap `GraphGen` class not require the full N(N-1)/2 calculations would require a lot of rewriting that isn't currently planned so I'm going to close this issue
