### ISSUE TITLE
Add Lomap conda package

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/Lomap#5]

**Comment by mikemhenry** [comment]
@richardjgowers I need to make a release/tag for conda-forge, should I start at `0.1` or start somewhere else?

**Comment by dwhswenson** [comment]
I'd vote `0.1` (or even `0.0.1`). We're not promising a stable API in Lomap at this point, are we? If we want the first "fully-ready" version to be `2.0`, we can always skip ahead to that.

**Comment by mikemhenry** [comment]
I like `0.0.1` since it says "here be dragons" and I agree, we can jump versions once we are happy with it

**Comment by IAlibay** [comment]
I guess the question is "how much development of Lomap are we offering"?

As far as I understand our brief was "get Lomap working" and that was it. If that's the case then we've hit our brief and this is version 1.0.0.

**Comment by richardjgowers** [comment]
There's also the fact that versions existed before us, so this is sort of v2-beta (we've broke stuff relative to v1 and this isn't everything we're breaking for v2)

**Comment by mikemhenry** [comment]
I guess it is @richardjgowers call, are we at `1.0.0` or do we have some dev to do? I just need a tag/release to build the conda-forge package, so if we can decide on something else later if we want. `2.0.0-pre` maybe? or something?

**Comment by mikemhenry** [comment]
This issue will be resolved once https://github.com/conda-forge/staged-recipes/pull/18154 is merged

**Comment by mikemhenry** [comment]
Added!
https://github.com/conda-forge/staged-recipes/pull/18154
