### ISSUE TITLE
Steps to move main development here

### ISSUE THREAD

**Issue by dwhswenson** [OpenFreeEnergy/Lomap#6]
This repo needs to not show as a fork of the old one. Being a fork will cause confusion, and people may try to contribute to the unmaintained upstream.

Since we decided against transferring the MobleyLab repo, we should detach our fork. https://support.github.com/request/fork

We should also ask that MobleyLab archive their Lomap repo, or at the very least add a note saying that development is continuing here (ideally both).

**Comment by davidlmobley** [comment]
Please do detach the fork, and I'm happy to deal with the LOMAP repo on my end. If it's archived, do you know if there's a way to make it point to this one instead? (People still may land there from previous publications.) If not, then I would add big disclaimers/pointers here.

**Comment by dwhswenson** [comment]
I don't think there's a way to forward the URL (transferring the repo can do that, but archiving it leaves it in place.) Usually people just do the big disclaimer with link at the top of their README file (something like "Continued development of LOMAP can be found at https://github.com/OpenFreeEnergy/Lomap"). Archiving makes the repo read-only, so you won't get more issues/comments after that (and it puts a banner to that effect at the top of every page), but all the history (like discussion of PRs) stays around.

**Comment by dwhswenson** [comment]
Detach fork request logged with GitHub support: https://support.github.com/ticket/personal/0/1575799

**Comment by davidlmobley** [comment]
OK, it sounds like this is a good plan then -- I'll handle the disclaimers/etc (or you can submit a PR to do it if you're ahead of me -- I'm backlogged) and then once those are in place I'll archive over there. 

I have an NIH proposal I'm submitting for a dev to do some other LOMAP stuff (with you) and it will help if we sort this out before they review it so it will be less confusing. :)

**Comment by dwhswenson** [comment]
Closed thanks to MobleyLab/Lomap#57. This is now the official place for further development!
